project_name: devops-wp-showcase
project_dir: /opt/devops-wp-showcase

timezone: Europe/Paris
ssh_port: 22 # this is the standart port
firewall_enabled: true

# Caddy / site
caddy_email: admin@yourdomain.tech
site_domain: yourdomainavallee.tech

# DB creds (pour Niveau 1: simple env file non versionn√©)
wp_db_name: wordpress_db_name
wp_db_user: wpuser_name
wp_db_password: "STRONG_Password_of_course"
wp_db_root_password: "STRONG_password_of_course"

