project_name: devops-wp-showcase
project_dir: /opt/devops-wp-showcase

timezone: Europe/Paris
ssh_port: 22
firewall_enabled: true

# Caddy / site
caddy_email: admin@lavallee.tech
site_domain: lavallee.tech

# DB creds (pour Niveau 1: simple env file non versionn√©)
wp_db_name: wordpress
wp_db_user: wpuser
wp_db_password: "CHANGE_ME_STRONG"
wp_db_root_password: "CHANGE_ME_ROOT_STRONG"

