# inventory/group_vars/wordpress_nodes.yml

db_backup_enabled: true

# Dump local
db_backup_dir: /opt/backups/mysql
db_backup_retention_days: 14

# Cron
db_backup_cron_hour: "2"
db_backup_cron_minute: "30"

# NFS Synology
db_backup_nfs_enabled: true
db_backup_nfs_server: "192.168.1.43"
db_backup_nfs_export: "/volume1/backup_db"
db_backup_nfs_mountpoint: "/mnt/backup_db"
db_backup_copy_to_nas: true
