hardening_os_fail2ban_enabled: true
hardening_os_sshd_jail_enabled: true

# SSH hardening
hardening_os_ssh_keys_only: true

# Firewall
hardening_os_firewall_enabled: true
hardening_os_ssh_allowed_cidrs:
  - 10.0.0.0/24
  - 192.168.1.0/24

# Optionnel (très propre) : n’autoriser le trafic HTTP vers le backend que depuis le proxy
hardening_os_restrict_http_to_proxy: true
hardening_os_proxy_ip: 10.0.0.10
hardening_os_backend_http_port: 8080
