hardening_fail2ban_enabled: true
hardening_bantime: 3600
hardening_maxretry: 5
hardening_findtime: 600

hardening_csp_enabled: true
hardening_block_xmlrpc: true
hardening_block_sensitive_files: true

caddy_log_path: /var/log/caddy/access.log
