- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: restart caddy container
  ansible.builtin.command:
    cmd: docker compose restart caddy
  args:
    chdir: "{{ proxy_dir }}"
  changed_when: true
