timezone: Europe/Paris
firewall_enabled: true
ssh_port: 22

# dirs
proxy_dir: /opt/devops-proxy
wp_dir: /opt/devops-wp

caddy_email: admin@lavallee.tech

sites:
  - name: lavallee
    domain: lavallee.tech
    backend_host: 10.0.0.13
    backend_port: 8080

  - name: wp2-news
    domain: news.lavallee.tech
    backend_host: 10.0.0.15
    backend_port: 8080
