$ANSIBLE_VAULT;1.1;AES256
30313263363333356562636436666665313433643039613263653664363462316163313431633165
6136656337623131376464333165623632356133383034370a393738386566646532643330316234
64323866333662656562313138383463656365653631636566613462363638613936616662303565
3962366561363538660a653636616561333035613733393932326434356266313033363664623839
66303738336436343938396437633932363366653438666663333764636262343732373066663861
61636162306161393038303866346433363730363336616465353234656461343439366336633863
64366561316433396339633533343833626665383932396261346533353933396334326134363338
64653535656163353632636662653366353861616664643335643034333030633438646662633931
39623266633636303235366165653462383139333364633133366432313136373435643531333663
32303533613830343232366435343264643265366162316435616166623535303732363037326164
36343563303236666536613663663933303161336435623363656338623231306364306235346631
38663664306532623730373566636538316564623962366633643832623931663832366336663130
33316134356535336465663937663439616166616662366437323334656230643431613138333732
39626664643732346363353336313065363336616630346238336465646332313562343534363432
34623565343230653638316131363632303038656463666662323131373139663138316262386236
31363461353835396235646338346433396332383330306635303337323830666538313139383465
61313135393762356536646632356366616165646362366635306334663137373637383131343438
65663565353061646138623563653464663464373539303830616464306533353036353366376235
33653436333565393639306438363764373765356636303236356133616236316263306630353732
39373934666661353739
